export interface Platform {
  slug:        string
  name:        string
  emoji:       string
  color:       string
  tagline:     string
  description: string
  formats:     string[]
  qualities:   string[]
  steps:       string[]
  faqs:        { q: string; a: string }[]
  features:    string[]
}

const PLATFORMS: Platform[] = [
  {
    slug: 'youtube-downloader',
    name: 'YouTube',
    emoji: '▶',
    color: 'from-red-600 to-red-700',
    tagline: 'Download YouTube Videos Free',
    description: 'Download any YouTube video, playlist, or channel in MP4, MP3, WebM, MKV and more. Supports HD, 4K, 8K. No account required.',
    formats: ['MP4','MP3','WebM','MKV','AVI','M4A','Opus'],
    qualities: ['Best','8K','4K','1080p','720p','480p','360p','Audio Only'],
    steps: ['Go to YouTube and copy the video URL from the address bar','Paste the URL into MediaDL above','Select your preferred format (MP4, MP3, etc.) and quality','Click Download — your file saves instantly'],
    faqs: [
      { q: 'Can I download entire YouTube playlists?', a: 'Yes! Use Playlist mode and paste the playlist URL. MediaDL will download all videos in your chosen format and quality.' },
      { q: 'What is the best quality for YouTube downloads?', a: 'Select "Best" to automatically download the highest available quality — up to 8K for supported videos.' },
      { q: 'Can I download YouTube audio only (MP3)?', a: 'Yes. Select MP3 or M4A format to extract audio only at 320kbps quality.' },
      { q: 'Is downloading YouTube videos legal?', a: 'Downloading for personal use varies by region. Always respect copyright and YouTube\'s Terms of Service.' },
    ],
    features: ['YouTube Shorts', 'YouTube Music', 'YouTube Playlists', 'YouTube Channels', 'Live Streams (recorded)', '8K UHD support'],
  },
  {
    slug: 'instagram-downloader',
    name: 'Instagram',
    emoji: '📷',
    color: 'from-pink-500 to-violet-600',
    tagline: 'Download Instagram Videos & Photos Free',
    description: 'Download Instagram reels, posts, stories, and IGTV videos in full HD quality. No watermark. No login required.',
    formats: ['MP4','JPG','PNG','WebP'],
    qualities: ['Original HD','1080p','720p'],
    steps: ['Open Instagram and copy the post/reel/story URL','Paste the URL into MediaDL above','Select format — MP4 for video, JPG for photo','Click Download to save instantly'],
    faqs: [
      { q: 'Can I download Instagram Reels?', a: 'Yes. Paste any Instagram Reel URL and download it as MP4 in full HD without any watermark.' },
      { q: 'Can I download Instagram Stories?', a: 'Yes, Instagram stories can be downloaded as MP4 (video) or JPG (photo) using their direct URL.' },
      { q: 'Does MediaDL add a watermark?', a: 'No watermarks are ever added. You get the original file exactly as it appears on Instagram.' },
      { q: 'Can I download private Instagram posts?', a: 'Paste your session cookies in Advanced Options to access your own private posts.' },
    ],
    features: ['Reels', 'Stories', 'Posts & Carousels', 'IGTV', 'Profile Photos', 'No Watermark'],
  },
  {
    slug: 'tiktok-downloader',
    name: 'TikTok',
    emoji: '♪',
    color: 'from-gray-900 to-gray-700',
    tagline: 'Download TikTok Videos Without Watermark',
    description: 'Download any TikTok video in HD quality without the TikTok watermark. Supports single videos and entire profiles.',
    formats: ['MP4','MP3','WebM'],
    qualities: ['Original HD','720p','480p'],
    steps: ['Copy the TikTok video URL from the app or browser','Paste the URL into MediaDL above','Choose format — MP4 for video, MP3 for audio','Click Download — no watermark, full quality'],
    faqs: [
      { q: 'Is the TikTok watermark removed?', a: 'MediaDL downloads the source video directly from TikTok\'s servers, bypassing the watermark overlay.' },
      { q: 'Can I download TikTok profiles?', a: 'Yes. Use Profile mode and paste the @username profile URL to download all public videos.' },
      { q: 'Can I download TikTok audio?', a: 'Yes. Select MP3 to extract the audio/music track from any TikTok video.' },
      { q: 'Are TikTok downloads in HD?', a: 'Yes. MediaDL always fetches the highest available quality from TikTok.' },
    ],
    features: ['No Watermark', 'Profile Downloads', 'Audio Extraction', 'Trending Videos', 'Sound Download', 'HD Quality'],
  },
  {
    slug: 'twitter-downloader',
    name: 'Twitter / X',
    emoji: '𝕏',
    color: 'from-gray-800 to-black',
    tagline: 'Download Twitter / X Videos & GIFs Free',
    description: 'Download videos, GIFs, and images from Twitter/X tweets in HD quality. Works with public tweets and media feeds.',
    formats: ['MP4','GIF','JPG','MP3'],
    qualities: ['Best HD','720p','480p','360p'],
    steps: ['Copy the tweet URL containing the video or image','Paste into MediaDL above','Select format (MP4 for video, GIF for animated content)','Click Download to save to your device'],
    faqs: [
      { q: 'Can I download Twitter GIFs?', a: 'Yes. Twitter GIFs are actually MP4 files. MediaDL downloads them as GIF or MP4.' },
      { q: 'Can I download from X (formerly Twitter)?', a: 'Yes. MediaDL works with both twitter.com and x.com URLs.' },
      { q: 'Can I download all media from a Twitter profile?', a: 'Use Profile mode with the URL https://x.com/username/media to download all profile media.' },
      { q: 'What quality is available for Twitter videos?', a: 'Twitter provides up to 720p HD. MediaDL always selects the best available quality.' },
    ],
    features: ['Videos & GIFs', 'Profile Media', 'Twitter Spaces (audio)', 'Thread Images', 'HD Quality', 'Spaces Recording'],
  },
  {
    slug: 'facebook-downloader',
    name: 'Facebook',
    emoji: 'f',
    color: 'from-blue-600 to-blue-800',
    tagline: 'Download Facebook Videos Free',
    description: 'Download public Facebook videos, Reels, and Watch content in HD or SD quality. No Facebook account needed for public videos.',
    formats: ['MP4','MP3','WebM'],
    qualities: ['HD','SD','Audio Only'],
    steps: ['Find the Facebook video and copy its URL','Paste the URL into MediaDL above','Select HD or SD quality','Click Download to save the video'],
    faqs: [
      { q: 'Can I download private Facebook videos?', a: 'For private videos, paste your Facebook cookies in Advanced Options to authenticate.' },
      { q: 'Can I download Facebook Reels?', a: 'Yes. Facebook Reels are fully supported — paste the reel URL and download as MP4.' },
      { q: 'What about Facebook Watch videos?', a: 'Yes. Facebook Watch videos can be downloaded by pasting the video page URL.' },
      { q: 'Is HD quality available for Facebook?', a: 'Yes, when the source video is in HD, MediaDL downloads at HD quality.' },
    ],
    features: ['Public Videos', 'Facebook Reels', 'Facebook Watch', 'Live (recorded)', 'HD & SD', 'Audio Only'],
  },
  {
    slug: 'reddit-downloader',
    name: 'Reddit',
    emoji: '👾',
    color: 'from-orange-500 to-red-600',
    tagline: 'Download Reddit Videos & Images Free',
    description: 'Download Reddit videos (v.redd.it), GIFs, and image galleries from any subreddit or user profile.',
    formats: ['MP4','GIF','JPG','PNG','WebP'],
    qualities: ['Best','1080p','720p','480p'],
    steps: ['Copy the Reddit post URL containing video or images','Paste into MediaDL above','Choose your format','Click Download — works on all subreddits'],
    faqs: [
      { q: 'Can I download Reddit hosted videos (v.redd.it)?', a: 'Yes. MediaDL downloads Reddit-hosted videos with their audio track properly merged.' },
      { q: 'Can I download Reddit image galleries?', a: 'Yes. For gallery posts, MediaDL scrapes all images and lets you select which to download.' },
      { q: 'What about Imgur or Gfycat linked on Reddit?', a: 'Yes. MediaDL supports Imgur albums, Gfycat, and most media hosts linked on Reddit.' },
      { q: 'Can I download NSFW Reddit content?', a: 'Public NSFW content can be downloaded. Add cookies for age-restricted subreddits.' },
    ],
    features: ['v.redd.it Videos', 'Image Galleries', 'GIF Downloads', 'Crossposts', 'Subreddit Archives', 'Audio Merge'],
  },
  {
    slug: 'vimeo-downloader',
    name: 'Vimeo',
    emoji: '🎬',
    color: 'from-teal-500 to-cyan-600',
    tagline: 'Download Vimeo Videos Free',
    description: 'Download public Vimeo videos in full HD, 2K, and 4K. Perfect for accessing your own uploaded content offline.',
    formats: ['MP4','WebM','MKV'],
    qualities: ['4K','2K','1080p','720p','540p','360p'],
    steps: ['Copy the Vimeo video URL','Paste it into MediaDL above','Select your preferred quality (up to 4K)','Click Download — fast server-side processing'],
    faqs: [
      { q: 'Can I download password-protected Vimeo videos?', a: 'For password-protected videos, enter the video URL with the password parameter or use cookies.' },
      { q: 'What is the maximum quality for Vimeo?', a: 'Vimeo supports up to 4K. MediaDL downloads the highest quality available.' },
      { q: 'Can I download from Vimeo channels?', a: 'Yes. Paste a Vimeo channel or album URL to download all videos in that collection.' },
      { q: 'Does Vimeo allow video downloads?', a: 'Public videos can be downloaded for personal use. Always respect the creator\'s copyright.' },
    ],
    features: ['4K Ultra HD', 'Channel Downloads', 'Vimeo Albums', 'Private Videos (with cookies)', 'Review Pages', 'Staff Picks'],
  },
  {
    slug: 'twitch-downloader',
    name: 'Twitch',
    emoji: '🎮',
    color: 'from-violet-600 to-purple-800',
    tagline: 'Download Twitch VODs & Clips Free',
    description: 'Download Twitch VODs (past broadcasts), highlights, and clips in HD quality. Also supports Twitch stream recordings.',
    formats: ['MP4','MKV','WebM'],
    qualities: ['Source Quality','1080p','720p','480p','360p'],
    steps: ['Go to Twitch and find the VOD or clip URL','Copy the URL from the address bar','Paste into MediaDL and choose quality','Click Download to save the VOD or clip'],
    faqs: [
      { q: 'Can I download Twitch VODs?', a: 'Yes. Paste any Twitch VOD URL (twitch.tv/videos/...) to download the full broadcast.' },
      { q: 'Can I download Twitch clips?', a: 'Yes. Twitch clips are fully supported — paste the clip URL to download in MP4.' },
      { q: 'What about subscriber-only VODs?', a: 'Add your Twitch cookies in Advanced Options to access subscriber-only content.' },
      { q: 'Can I download in source quality?', a: 'Yes. Select "Source Quality" to download the original uncompressed stream recording.' },
    ],
    features: ['VODs', 'Clips', 'Highlights', 'Source Quality', 'Channel Archives', 'Subscriber Content (with cookies)'],
  },
  {
    slug: 'pinterest-downloader',
    name: 'Pinterest',
    emoji: '📌',
    color: 'from-red-600 to-red-800',
    tagline: 'Download Pinterest Images & Videos Free',
    description: 'Download Pinterest pins, boards, and videos in original quality. Bulk download entire Pinterest boards.',
    formats: ['JPG','PNG','WebP','MP4','GIF'],
    qualities: ['Original','High Quality','Standard'],
    steps: ['Open Pinterest and copy the pin or board URL','Paste into MediaDL above','Choose format — JPG for images, MP4 for video pins','Click Download to save all selected items'],
    faqs: [
      { q: 'Can I download an entire Pinterest board?', a: 'Yes. Use Profile mode with the board URL to download all pins from that board.' },
      { q: 'What quality are Pinterest downloads?', a: 'MediaDL downloads pins at their original uploaded quality — the highest available.' },
      { q: 'Can I download Pinterest videos?', a: 'Yes. Video pins are downloaded as MP4 in the best available quality.' },
      { q: 'Can I download from Pinterest without an account?', a: 'Yes. MediaDL works with all public Pinterest content without any login.' },
    ],
    features: ['Single Pins', 'Board Downloads', 'Video Pins', 'GIF Pins', 'Original Quality', 'Bulk Download'],
  },
  {
    slug: 'soundcloud-downloader',
    name: 'SoundCloud',
    emoji: '☁',
    color: 'from-orange-400 to-orange-600',
    tagline: 'Download SoundCloud Tracks & Playlists Free',
    description: 'Download SoundCloud tracks, playlists, and artist discographies as high-quality MP3 files.',
    formats: ['MP3','M4A','Opus','OGG','FLAC'],
    qualities: ['Best (320kbps)','256kbps','128kbps'],
    steps: ['Copy the SoundCloud track or playlist URL','Paste into MediaDL above','Select audio format (MP3 at 320kbps recommended)','Click Download to save the audio file'],
    faqs: [
      { q: 'What audio quality is available on SoundCloud?', a: 'SoundCloud Go+ tracks support 256kbps AAC. Free tracks are typically 128kbps. MediaDL downloads the best available.' },
      { q: 'Can I download SoundCloud playlists?', a: 'Yes. Use Playlist mode to download entire SoundCloud playlists or an artist\'s complete discography.' },
      { q: 'Can I download private SoundCloud tracks?', a: 'Yes, if you have access. Add your SoundCloud cookies in Advanced Options.' },
      { q: 'What format should I choose for music?', a: 'MP3 at 320kbps is the most compatible. Choose M4A for better quality at the same file size.' },
    ],
    features: ['Tracks & Albums', 'Playlists', 'Artist Profiles', '320kbps MP3', 'M4A/AAC', 'SoundCloud Go+'],
  },
  {
    slug: 'dailymotion-downloader',
    name: 'Dailymotion',
    emoji: '▶',
    color: 'from-blue-500 to-blue-700',
    tagline: 'Download Dailymotion Videos Free',
    description: 'Download any Dailymotion video in HD quality. Supports channels, playlists, and all public content.',
    formats: ['MP4','WebM','MP3'],
    qualities: ['1080p','720p','480p','360p','240p'],
    steps: ['Copy the Dailymotion video URL','Paste it into MediaDL above','Select quality and format','Click Download to save the video'],
    faqs: [
      { q: 'What is the max quality on Dailymotion?', a: 'Dailymotion supports up to 1080p HD. MediaDL selects the best available quality.' },
      { q: 'Can I download Dailymotion channels?', a: 'Yes. Use Playlist mode with a channel URL to download all channel videos.' },
      { q: 'Are embedded Dailymotion videos supported?', a: 'Paste the original video URL (dailymotion.com/video/...) for best results.' },
      { q: 'Is Dailymotion downloading free?', a: 'Yes, completely free with no limits or registration required.' },
    ],
    features: ['HD Downloads', 'Channel Support', 'Playlist Mode', 'Embeds', 'MP3 Extraction', 'Batch Download'],
  },
  {
    slug: 'tumblr-downloader',
    name: 'Tumblr',
    emoji: 't',
    color: 'from-indigo-600 to-blue-800',
    tagline: 'Download Tumblr Videos & Images Free',
    description: 'Download Tumblr videos, GIFs, and images from posts and blogs in original quality.',
    formats: ['MP4','GIF','JPG','PNG','WebP'],
    qualities: ['Original','HD','Standard'],
    steps: ['Copy the Tumblr post URL','Paste into MediaDL above','Choose format (GIF keeps animation, MP4 for video)','Click Download to save'],
    faqs: [
      { q: 'Can I download Tumblr GIFs?', a: 'Yes. Tumblr GIFs are downloaded as animated GIFs or as MP4 (smaller file size).' },
      { q: 'Can I download all posts from a Tumblr blog?', a: 'Use Profile mode with the blog URL to download all media from a Tumblr blog.' },
      { q: 'What about NSFW Tumblr content?', a: 'Public NSFW Tumblr content is supported. Add cookies for age-gated content.' },
      { q: 'Can I download Tumblr videos?', a: 'Yes. All Tumblr video posts are supported, including Tumblr-hosted and embedded videos.' },
    ],
    features: ['Video Posts', 'GIF Downloads', 'Image Sets', 'Blog Archives', 'Reblog Sources', 'Adult Content Support'],
  },
  {
    slug: 'flickr-downloader',
    name: 'Flickr',
    emoji: '🌸',
    color: 'from-pink-500 to-rose-600',
    tagline: 'Download Flickr Photos & Albums Free',
    description: 'Download Flickr photos and entire albums in original resolution. Perfect for archiving your own Flickr content.',
    formats: ['JPG','PNG','TIFF','WebP'],
    qualities: ['Original','Large 2048','Medium 800','Small 400'],
    steps: ['Copy the Flickr photo or album URL','Paste into MediaDL above','Select size — Original for maximum quality','Click Download to save all selected photos'],
    faqs: [
      { q: 'Can I download Flickr albums?', a: 'Yes. Paste a Flickr album or set URL to download all photos in original resolution.' },
      { q: 'What is the maximum Flickr photo quality?', a: 'Original size downloads the photo at its native uploaded resolution — often 20+ megapixels.' },
      { q: 'Can I download my own Flickr photos?', a: 'Yes. Add your Flickr cookies to access and download your private photos.' },
      { q: 'Does Flickr allow photo downloads?', a: 'Public photos under appropriate licenses can be downloaded for personal and permitted uses.' },
    ],
    features: ['Original Resolution', 'Album Downloads', 'Photostream', 'Groups', 'Galleries', '20MP+ Quality'],
  },
  {
    slug: 'imgur-downloader',
    name: 'Imgur',
    emoji: '🖼',
    color: 'from-green-600 to-green-800',
    tagline: 'Download Imgur Images & Albums Free',
    description: 'Download Imgur images, GIF/MP4 animations, and entire albums in original quality. Fast and unlimited.',
    formats: ['JPG','PNG','GIF','MP4','WebM'],
    qualities: ['Original','Huge','Large','Medium'],
    steps: ['Copy the Imgur image or album URL','Paste into MediaDL above','Choose format — GIF for animations, JPG for photos','Click Download to save everything'],
    faqs: [
      { q: 'Can I download entire Imgur albums?', a: 'Yes. Paste any Imgur album URL to download all images and GIFs in the album.' },
      { q: 'Are Imgur GIFVs supported?', a: 'Yes. Imgur GIFV files are downloaded as MP4 (more efficient) or GIF (classic format).' },
      { q: 'What is the maximum Imgur quality?', a: 'MediaDL downloads at original upload quality — typically up to 20MB per image.' },
      { q: 'Can I download from Imgur galleries?', a: 'Yes. Public Imgur galleries and front page posts are fully supported.' },
    ],
    features: ['Single Images', 'Albums', 'GIFV Support', 'Gallery Posts', 'Original Quality', 'Bulk Download'],
  },
  {
    slug: 'bilibili-downloader',
    name: 'Bilibili',
    emoji: '📺',
    color: 'from-cyan-500 to-blue-600',
    tagline: 'Download Bilibili Videos Free',
    description: 'Download Bilibili videos in HD quality. Supports Chinese and international Bilibili content.',
    formats: ['MP4','MKV','MP3','M4A'],
    qualities: ['1080P+','1080p','720p','480p','360p'],
    steps: ['Copy the Bilibili video URL (BV or AV number)','Paste into MediaDL above','Select video quality (1080P+ for premium quality)','Click Download to save the video'],
    faqs: [
      { q: 'Can I download Bilibili videos without a VPN?', a: 'Yes. MediaDL handles region detection automatically for international content.' },
      { q: 'Do I need a Bilibili account?', a: 'For premium (1080P+) quality, add your Bilibili cookies. Free content works without login.' },
      { q: 'Can I download Bilibili audio only?', a: 'Yes. Select MP3 or M4A to extract only the audio track from Bilibili videos.' },
      { q: 'Are Bilibili subtitles supported?', a: 'Yes. Enable subtitles in Advanced Options to download and embed Chinese/English subtitles.' },
    ],
    features: ['1080P+ Quality', 'Danmaku Support', 'Audio Only', 'Subtitle Download', 'Season Downloads', 'Multi-part Videos'],
  },
]

export function getPlatformBySlug(slug: string): Platform | undefined {
  return PLATFORMS.find((p) => p.slug === slug)
}

export function getAllPlatformSlugs(): string[] {
  return [...new Set(PLATFORMS.map((p) => p.slug))]
}

export { PLATFORMS }
