apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mediadl

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - mysql.yaml
  - redis.yaml
  - kafka.yaml
  - python-service.yaml
  - backend.yaml
  - frontend.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/name: mediadl
  app.kubernetes.io/managed-by: kustomize
